GET http://localhost:3001/api/persons

###
PUT http://localhost:3001/api/persons/692859add27ced9125476a8c HTTP/1.1
content-type: application/json

{
    "name": "Testar Testsson",
    "number": "46-12-3456789"
}